language: node_js

node_js:
  - "8"

install:
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run test:travis

after_success:
  - npm run codecov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov

env:
  global:
    - COOKIE_SECRET=somethingverysecrethere
    - GOOGLE_ANALYTICS_PROPERTY_ID=ga-test
